

# Blog Setting
title: Lhts4u 
# logo: "images/logo.svg" # You can add own logo image.
description: All the time becomes the past.
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: lhts4u
  bio: 안녕! 내 이름은 배수한(aka.lhts4u)이야. 모든 시간들은 과거가 된다. 또한 그 시간들이 나를 만든다. Hi! My name is Suhan Bae(aka.lhts4u). All the time becomes the past. Also, those times make me.
  
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
email: ss910204@gmail.com # Add your Email address
instagram: https://instagram.com/lhts4u # Add your Instagram handle
linkedin: https://www.linkedin.com/in/kuro-ab7987155/ # Add your Linkedin address
github: https://github.com/lhts4u/ # Add your Github address

# Hero Section
hero: false # To enable the section hero, use the value true. To turn off use the value false.
hero-title: All the time becomes the past. # Add your hero title
hero-subtitle: Tomorrow will be better than yesterday than today. # Add your hero subtitle
hero-image: images/main.jpg # Add background image in section hero

# Footer
footer-image: images/main.jpg # Add background image in footer

# Comment Section (Disqus)
disqus-identifier: lhts4u # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 3
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed